version: '3.7'

services:
  keycloak-db:
    image: postgres:14
    volumes:
      - keycloak-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${KEYCLOAK_JDBC_DB:-keycloak}
      POSTGRES_USER: ${KEYCLOAK_JDBC_USER:-admin}
      POSTGRES_PASSWORD: ${KEYCLOAK_JDBC_PASSWORD:-changeme}
    networks:
      - formsflow

  keycloak:
    image: quay.io/keycloak/keycloak:14.0.0
    volumes:
      - ./configuration/imports:/opt/jboss/keycloak/imports
    command:
      - "-b"
      - "0.0.0.0"
      - "-Djboss.http.port=8080"
      - "-Dkeycloak.import=/opt/jboss/keycloak/imports/formsflow-ai-realm.json"
      - "-Dkeycloak.migration.strategy=OVERWRITE_EXISTING"
    environment:
      - JBOSS_HOME=/opt/jboss/keycloak
      - DB_VENDOR=POSTGRES
      - DB_ADDR=keycloak-db
      - DB_PORT=5432
      - DB_DATABASE=${KEYCLOAK_JDBC_DB:-keycloak}
      - DB_USER=${KEYCLOAK_JDBC_USER:-admin}
      - DB_PASSWORD=${KEYCLOAK_JDBC_PASSWORD:-changeme}
      - KEYCLOAK_USER=${KEYCLOAK_ADMIN_USER:-admin}
      - KEYCLOAK_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD:-changeme}
    ports:
      - "8080:8080"
    networks:
      - formsflow

networks:
  formsflow:
    driver: overlay

volumes:
  keycloak-data:
    driver: local
