name: Forms flow DEV CD

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: .

jobs:
  deploy-to-oc-multi-tenancy-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login Openshift
        shell: bash
        run: |
          oc login --server=${{secrets.OPENSHIFT4_LOGIN_REGISTRY}} --token=${{secrets.OPENSHIFT_SA_DEV_MULTITENANCY_TOKEN}} --insecure-skip-tls-verify
      - name: Watch new rollout (trigger by image change in Openshift)
        shell: bash
        run: |
          oc project ffp-dev
          oc rollout latest dc/forms-flow-web
          oc rollout status dc/forms-flow-web
          
          oc scale deployment/forms-flow-admin --replicas=0
          oc scale deployment/forms-flow-admin --replicas=1
          oc scale deployment/forms-flow-forms --replicas=0
          oc scale deployment/forms-flow-forms --replicas=1
          oc scale deployment/forms-flow-bpm --replicas=0
          oc scale deployment/forms-flow-bpm --replicas=1
          oc scale deployment/forms-flow-api --replicas=0
          oc scale deployment/forms-flow-api --replicas=1
          oc scale deployment/forms-flow-data-analysis --replicas=0
          oc scale deployment/forms-flow-data-analysis --replicas=1
          oc scale deployment/forms-flow-analytics-server --replicas=0
          oc scale deployment/forms-flow-analytics-server --replicas=1
          
  deploy-to-oc-dev:
    needs: deploy-to-oc-multi-tenancy-dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login Openshift
        shell: bash
        run: |
          oc login --server=${{secrets.OPENSHIFT4_LOGIN_REGISTRY}} --token=${{secrets.OPENSHIFT_SA_DEV_TOKEN}} --insecure-skip-tls-verify
      - name: Watch new rollout (trigger by image change in Openshift)
        shell: bash
        run: |
          oc project ff-dev
          oc rollout latest dc/forms-flow-web
          oc rollout status dc/forms-flow-web
          
          oc scale deployment/forms-flow-forms --replicas=0
          oc scale deployment/forms-flow-forms --replicas=1
          oc scale deployment/forms-flow-bpm --replicas=0
          oc scale deployment/forms-flow-bpm --replicas=1
          oc scale deployment/forms-flow-api --replicas=0
          oc scale deployment/forms-flow-api --replicas=1
          oc scale deployment/forms-flow-data-analysis --replicas=0
          oc scale deployment/forms-flow-data-analysis --replicas=1
          oc scale deployment/forms-flow-analytics-server --replicas=0
          oc scale deployment/forms-flow-analytics-server --replicas=1
